[package]
name = 'substrate-service-discovery-module'
version = '1.0.0'
authors = ['Joystream contributors']
edition = '2018'

[features]
default = ['std']
std = [
	'sr-primitives/std',
	'srml-support/std',
	'system/std',
	'rstd/std',
	'serde',
    'codec/std',
    'primitives/std',
    'bureaucracy/std',
]

[dependencies.sr-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-primitives'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.srml-support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-support'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.common]
default_features = false
package = 'substrate-common-module'
path = '../common'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-system'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-std'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.1.0'

[dev-dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dependencies.bureaucracy]
default_features = false
package = 'substrate-bureaucracy-module'
path = '../bureaucracy'

[dev-dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-balances'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'

[dev-dependencies.recurringrewards]
default_features = false
package = 'substrate-recurring-reward-module'
path = '../recurring-reward'

[dev-dependencies.hiring]
default_features = false
package = 'substrate-hiring-module'
path = '../hiring'

[dev-dependencies.stake]
default_features = false
package = 'substrate-stake-module'
path = '../stake'

[dev-dependencies.minting]
default_features = false
package = 'substrate-token-mint-module'
path = '../token-minting'

[dev-dependencies.membership]
default_features = false
package = 'substrate-membership-module'
path = '../membership'

[dev-dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-timestamp'
rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'