language: rust

rust:
  - 1.43.0

matrix:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf
      services: docker
    - os: osx
      env: TARGET=x86_64-apple-darwin

before_install:
  - rustup component add rustfmt
  - cargo fmt --all -- --check
  - rustup component add clippy
  - BUILD_DUMMY_WASM_BINARY=1 cargo clippy -- -D warnings
  - rustup default stable
  - rustup update nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - cargo test --verbose --all

install:
  - |
    if [ "$TARGET" = "arm-unknown-linux-gnueabihf" ]
    then
      docker pull joystream/rust-raspberry
    fi

script:
  - |
    if [ "$TARGET" = "arm-unknown-linux-gnueabihf" ]
    then
      docker run -u root \
        --volume ${TRAVIS_BUILD_DIR}:/home/cross/project \
          joystream/rust-raspberry \
        build --release
      sudo chmod a+r ${TRAVIS_BUILD_DIR}/target/${TARGET}/release/joystream-node
    else
      cargo build --release --target=${TARGET}
    fi

before_deploy:
  - cp ./target/${TARGET}/release/joystream-node .
  - |
    if [ "$TARGET" = "arm-unknown-linux-gnueabihf" ]
    then
      export FILENAME="joystream-node-armv7-linux-gnueabihf"
    else
      export FILENAME=`./joystream-node --version | sed -e "s/ /-/g"`
    fi
  - tar -cf ${FILENAME}.tar ./joystream-node
  - gzip ${FILENAME}.tar

deploy:
  - provider: releases
    api_key:
      secure: QTna4XzKmPrXNA5KnYfLsH8cAKxESLdFbQ5HJ6nvB9reE10SVtg8lZ+ShL+no7TACNBUNt09Qv9HNgs6JcNRJ9QMHEJHKIbMyjplhBtZ+W3l0k+6TL0yeKHZ/OvddDF+vDbpN+y4xBfOf0xqZcNH3lZJTms/NPBn/KT5DpQ3JZ8bibdMP2HSCazfvHLwj38OuLX6VWbFcmN2RAmUR9AXYvk5wWYVw8g1VDzTCxjH1G+dGWH1L9+ZDgFfv7BNSNhPc6V9GghgLVZ+37r/STzTTAQ/gPv+yruglEWUhSAngFfVYUegvTmIeQLi/V+g0tKUS+l7eNX08xz6eZcn0+/32V7P+oEN/dhU84E0kgmiOsiUEGI/KFM+qw9TyX3GtD67UmG5TZrD7OUMIu1qCuPSetsTOK2kvpwlYAn+j5iFB30Uz4hXhOH5dib2zz2I7cYHi1kvzeNQqQOPNDCmaO48bcbRIaeqMAHdsb6scGzh/+CD2V2HOmHlhd+4o1PpX6hAMwmOXAu3bMDi4zlB9Hb1cSZnsYNBHawkD6y45QGepFKpGW/6u5VRPeMK62Gm9wu815C36B4mVg6CVqtZMbk0WYPIk6zfoTft3i04YthKbRO96a5VD9LssVbiSYnudXuZJjSllSZVCi9AKS8JVIS2jC2z+tWkquAesSrwztriRcs=
    file: ${FILENAME}.tar.gz
    on:
      tags: true
      repo: Joystream/joystream
    draft: true
    overwrite: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: QTna4XzKmPrXNA5KnYfLsH8cAKxESLdFbQ5HJ6nvB9reE10SVtg8lZ+ShL+no7TACNBUNt09Qv9HNgs6JcNRJ9QMHEJHKIbMyjplhBtZ+W3l0k+6TL0yeKHZ/OvddDF+vDbpN+y4xBfOf0xqZcNH3lZJTms/NPBn/KT5DpQ3JZ8bibdMP2HSCazfvHLwj38OuLX6VWbFcmN2RAmUR9AXYvk5wWYVw8g1VDzTCxjH1G+dGWH1L9+ZDgFfv7BNSNhPc6V9GghgLVZ+37r/STzTTAQ/gPv+yruglEWUhSAngFfVYUegvTmIeQLi/V+g0tKUS+l7eNX08xz6eZcn0+/32V7P+oEN/dhU84E0kgmiOsiUEGI/KFM+qw9TyX3GtD67UmG5TZrD7OUMIu1qCuPSetsTOK2kvpwlYAn+j5iFB30Uz4hXhOH5dib2zz2I7cYHi1kvzeNQqQOPNDCmaO48bcbRIaeqMAHdsb6scGzh/+CD2V2HOmHlhd+4o1PpX6hAMwmOXAu3bMDi4zlB9Hb1cSZnsYNBHawkD6y45QGepFKpGW/6u5VRPeMK62Gm9wu815C36B4mVg6CVqtZMbk0WYPIk6zfoTft3i04YthKbRO96a5VD9LssVbiSYnudXuZJjSllSZVCi9AKS8JVIS2jC2z+tWkquAesSrwztriRcs=
    file: ${FILENAME}.tar.gz
    on:
      branch: development
      repo: Joystream/joystream
    draft: true
    prerelease: true
    overwrite: true
    skip_cleanup: true
