language: rust

rust:
  - 1.41.1

os:
  - linux
  - osx

before_script:
  - rustup component add rustfmt --toolchain 1.41.1-x86_64-unknown-linux-gnu
  - rustup update nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - cargo +nightly install --git https://github.com/alexcrichton/wasm-gc --force

script:
  - cargo fmt --all -- --check
  - cargo build --release
  - mv ./target/release/joystream-node .
  - export FILENAME=`./joystream-node --version | sed -e "s/ /-/g"`
  - tar -cf ${FILENAME}.tar ./joystream-node
  - gzip ${FILENAME}.tar

deploy:
  provider: releases
  api_key:
    secure: icPiO8fnOgkHlo2MpUJvH+sZSaxJqzHif/1Pndlxg2jM/jrvLbUCr9UvtLaRQYPi2BVnR41t2m56uMJD3LktKMzAwUP74JcdX7iw6tq+iyvuU4UBsn5+k8pgue+eE34PVN0vNbDS+RVzzc6wG/vhUyKNKz6M1pOuEBx0s6UX3oED16W1LEN8/CHmFVBxQehlGv40Mje6tSmfZMw++efAmFm9vd0Fx8ub8as5ZqyjGv2IwbQlyIGT3SF9yx2va90F2wOxyZM7wgWzA/XIzlDGy+zvZssEYNGQhepUdGwTwwe+YLvZWuttTC218K4H8aireO2vCMti58veX7hVuDz6j6ETVxhr6Nv47HfxQF4IywDTUH1JGlLVadgcKQXUlVRrfy1tBKDq76ppMul8TdS0LgojeTgcJOblKw0V5TMwx+IYmMabVIZQ7Q7xKqf4SeXxh/YL3EUWBvzu1TUn946CB3jLATUxjGyjAZ00BN01QL7chrkcewInlKxJ/wjUqM34KnHNXXgPNADW+c5IIsl82BwnPsPK37WMfW5FaKtOn0YXQWj9QwtEX7VakNnPZZRvpsl2Ftd1As7hPgufMk8NbXmiQH8i0h1W0xcHQ38hvegIpf1fa8JA7VIFBP6ElymMTIus5xD5rsLGzPqgazm/328p2DthJWebyLAZIbEX+I4=
  file: ${FILENAME}.tar.gz
  on:
    tags: true
    branch: development
  draft: true
  prerelease: true
  overwrite: true
