language: node_js

node_js:
    - 10
    - 12
    - 13

services:
  - docker

script:
  - docker-compose -f ./scripts/compose/devchain-and-ipfs-node/docker-compose.yaml up
  - yarn test
  - docker-compose -f ./scripts/compose/devchain-and-ipfs-node/docker-compose.yaml down

