language: rust

rust:
  - 1.41.1

cache:
  cargo

os:
  - linux
  - osx
# - windows

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export TARGET=x86_64-apple-darwin  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export TARGET=x86_64-unknown-linux-gnu  ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export TARGET=x86_64-pc-windows-msvc  ; fi
  - rustup component add rustfmt
  - rustup update nightly
  - rustup target add ${TARGET}
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - rustup show

script:
  - cargo fmt --all -- --check
  - cargo build --release --target=${TARGET}
  - mv ./target/${TARGET}/release/joystream-node .
  - export FILENAME=`./joystream-node --version | sed -e "s/ /-/g"`
  - tar -cf ${FILENAME}.tar ./joystream-node
  - gzip ${FILENAME}.tar

deploy:
  - provider: releases
    api_key:
      secure: fAfOHxF+yiUqqTRPT2q3SvKXgjGhb6FhH1musNNr2179Onjt0eFVD5vTPb3VJ6BtpxXyo5PJTCtGoGmKaYmvtyFukhbOnwyYWh7h13bV90QiNwqj2bxtH/fdYOLkvkFdNHSr12Gdwf4F+mKHLy0wLqra7bt7fMVhZPsMwIbV7vigAPXpgWn/9zhxXtDjrswevBTmQtrx5umHkRHn5r3R4bXyrXvW8WMjA6/X2NwYFQrVHGEjpG1hOGQj1JWopYVs0hN+3FjVs3n+RHJrtk0ApUg6d7qtYqTkzDn7mwRyrXPym96RbhpzarM5YWcFAHDPLD2/E/KTgDjNciZdmHnjcUTNoFfoGByPmtuUGgpO2jf8+1V5fGxpW/dFis7swOLaMDWf4d2ndFubcPVSUOKKgxOOdXRs9auQCwT5rvR4lJALT2W4sgEp11fwW+qIJxpKWq4AHTWJCWlIBVCToJJ3FNTOMvyLkExfquF/kG5nO5XVjqg+eCLzTjcB91EwAmZBndHCx2ZfUuo4j3lxZLanpQIqsLiM/EhOVvany1pdJvNl3ncV/4PuBbvhmd1eqzeS2yRWeE16c0UpJ193drFurQ50GDr+Npo/qOE9DIeevZnwGzcNeAI7tK6XYQoEphluYMZa7xGGi7ix+MMq4utN7qJii2++wmWHG0gruiTdrZ8=
    file: ${FILENAME}.tar.gz
    skip_cleanup: true
    on:
      tags: true
      repo: Joystream/substrate-node-joystream
    draft: true
    overwrite: true
  - provider: releases
    api_key:
      secure: fAfOHxF+yiUqqTRPT2q3SvKXgjGhb6FhH1musNNr2179Onjt0eFVD5vTPb3VJ6BtpxXyo5PJTCtGoGmKaYmvtyFukhbOnwyYWh7h13bV90QiNwqj2bxtH/fdYOLkvkFdNHSr12Gdwf4F+mKHLy0wLqra7bt7fMVhZPsMwIbV7vigAPXpgWn/9zhxXtDjrswevBTmQtrx5umHkRHn5r3R4bXyrXvW8WMjA6/X2NwYFQrVHGEjpG1hOGQj1JWopYVs0hN+3FjVs3n+RHJrtk0ApUg6d7qtYqTkzDn7mwRyrXPym96RbhpzarM5YWcFAHDPLD2/E/KTgDjNciZdmHnjcUTNoFfoGByPmtuUGgpO2jf8+1V5fGxpW/dFis7swOLaMDWf4d2ndFubcPVSUOKKgxOOdXRs9auQCwT5rvR4lJALT2W4sgEp11fwW+qIJxpKWq4AHTWJCWlIBVCToJJ3FNTOMvyLkExfquF/kG5nO5XVjqg+eCLzTjcB91EwAmZBndHCx2ZfUuo4j3lxZLanpQIqsLiM/EhOVvany1pdJvNl3ncV/4PuBbvhmd1eqzeS2yRWeE16c0UpJ193drFurQ50GDr+Npo/qOE9DIeevZnwGzcNeAI7tK6XYQoEphluYMZa7xGGi7ix+MMq4utN7qJii2++wmWHG0gruiTdrZ8=
    file: ${FILENAME}.tar.gz
    skip_cleanup: true
    on:
      branch: development
      repo: Joystream/substrate-node-joystream
    draft: true
    prerelease: true
    overwrite: true
