language: rust

rust:
  - 1.40.0
# Caching saves a lot of time but often causes stalled builds...
# disabled for now
# look into solution here: https://levans.fr/rust_travis_cache.html
# cache:
#  - cargo

before_script:
  # Do a self update before installing rustfmt - https://github.com/rust-lang/rustfmt/issues/3271
  - rustup self update
  - rustup component add rustfmt
  - ./setup.sh

script:
  # Ensure all checked in code is cargo-fmt'ed
  - cargo fmt --all -- --check
  # Native build and unit tests check
  - cargo test --verbose --all
  # WASM build check
  - cargo build
