[package]
name = "joystream-node"
version = "0.9.0"
authors = ["Jsgenesis <contact@jsgenesis.com>"]
build = "build.rs"

[[bin]]
name = "joystream-node"
path = "src/main.rs"

[dependencies]
error-chain = "0.12"
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
tokio = "0.1.7"
exit-future = "0.1"
parking_lot = "0.4"
hex-literal = "0.1"
slog = "^2"
parity-codec = { version = "2.2" }
trie-root = { git = "https://github.com/paritytech/trie", rev = "2616db2a" }
sr-io = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-cli = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-executor = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-service = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-inherents = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-network = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-consensus-aura = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-client = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", default-features = false }
substrate-finality-grandpa = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-basic-authorship = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
joystream-node-runtime = { path = "runtime" }
node-executor = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
structopt = "0.2.13"

[build-dependencies]
vergen = "2"

[workspace]
members = [ "runtime" ]
exclude = [ "runtime/wasm" ]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
