[package]
authors = ['Joystream']
edition = '2018'
name = 'joystream-node-runtime'
version = '4.1.0'

[features]
default = ['std']
std = [
    'parity-codec/std',
    'parity-codec-derive/std',
    'primitives/std',
    'substrate-client/std',
    'rstd/std',
    'runtime-io/std',
    'srml-support/std',
    'balances/std',
    'executive/std',
    'aura/std',
    'indices/std',
    'primitives/std',
    'system/std',
    'timestamp/std',
    'sudo/std',
    'version/std',
    'serde_derive',
    'serde/std',
    'safe-mix/std',
    'consensus-aura/std',
    'staking/std',
    'session/std',
    'offchain-primitives/std',
    'consensus-authorities/std',
    'grandpa/std',
    'finality-tracker/std',
]
[dependencies.aura]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-aura'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.balances]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-balances'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.consensus]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-consensus'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.consensus-aura]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'substrate-consensus-aura-primitives'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.executive]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-executive'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.indices]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-indices'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.parity-codec]
default-features = false
version = '3.1'

[dependencies.parity-codec-derive]
default-features = false
version = '3.1'

[dependencies.primitives]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'substrate-primitives'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.rstd]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'sr-std'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'sr-io'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'sr-primitives'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.safe-mix]
default-features = false
version = '1.0'

[dependencies.serde]
default-features = false
version = '1.0'

[dependencies.serde_derive]
optional = true
version = '1.0'

[dependencies.srml-support]
default_features = false
git = 'https://github.com/joystream/substrate.git'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.substrate-client]
default_features = false
git = 'https://github.com/joystream/substrate.git'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.sudo]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-sudo'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.system]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-system'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-timestamp'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.version]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'sr-version'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.staking]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-staking'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.session]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-session'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.offchain-primitives]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'substrate-offchain-primitives'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.consensus-authorities]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'substrate-consensus-authorities'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.grandpa]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-grandpa'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'

[dependencies.finality-tracker]
default_features = false
git = 'https://github.com/joystream/substrate.git'
package = 'srml-finality-tracker'
rev = '59d5ec144704cec017a01f3e4dbb6b73c5542bf7'