[dependencies]
error-chain = '0.12'
exit-future = '0.1'
futures = '0.1'
hex-literal = '0.1'
log = '0.4'
parity-codec = '3.0'
parking_lot = '0.7.1'
slog = '^2'
tokio = '0.1'
trie-root = '0.11.0'

[dependencies.basic-authorship]
git = 'https://github.com/joystream/substrate.git'
package = 'substrate-basic-authorship'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.consensus]
git = 'https://github.com/joystream/substrate.git'
package = 'substrate-consensus-aura'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.ctrlc]
features = ['termination']
version = '3.0'

[dependencies.inherents]
git = 'https://github.com/joystream/substrate.git'
package = 'substrate-inherents'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.node-executor]
git = 'https://github.com/joystream/substrate.git'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.joystream-node-runtime]
git = 'https://github.com/joystream/substrate-runtime-joystream.git'
tag = 'v3.4.0'
# When developing locally change the location of the dependency to a local directory
# comment out the "git" and "tag" lines above and replace with a "path"
# path = 'runtime'
# path = '../my-local-joystream-runtime-repo/'

[dependencies.primitives]
git = 'https://github.com/joystream/substrate.git'
package = 'substrate-primitives'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.sr-io]
git = 'https://github.com/joystream/substrate.git'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.substrate-cli]
git = 'https://github.com/joystream/substrate.git'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.substrate-client]
git = 'https://github.com/joystream/substrate.git'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.substrate-executor]
git = 'https://github.com/joystream/substrate.git'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.substrate-network]
git = 'https://github.com/joystream/substrate.git'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.substrate-service]
git = 'https://github.com/joystream/substrate.git'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[dependencies.transaction-pool]
git = 'https://github.com/joystream/substrate.git'
package = 'substrate-transaction-pool'
rev = 'df5e65927780b323482e2e8b5031822f423a032d'

[package]
authors = ['Joystream']
build = 'build.rs'
edition = '2018'
name = 'joystream-node'
version = '0.10.1'

[[bin]]
name = 'joystream-node'
path = 'src/main.rs'

[build-dependencies]
vergen = '3'
[profile.release]
panic = 'unwind'
