[package]
authors = ['Joystream']
edition = '2018'
name = 'joystream-node-runtime'
version = '6.0.0'

[features]
default = ['std']
no_std = []
std = [
    'authority-discovery-primitives/std',
    'authority-discovery/std',
    'authorship/std',
    'finality-tracker/std',
    'im-online/std',
    'session/std',
    'offences/std',
    'sr-staking-primitives/std',
    'staking/std',
    'codec/std',
    'substrate-client/std',
    'rstd/std',
    'runtime-io/std',
    'srml-support/std',
    'balances/std',
    'babe/std',
    'babe-primitives/std',
    'executive/std',
    'indices/std',
    'grandpa/std',
    'primitives/std',
    'runtime-primitives/std',
    'system/std',
    'timestamp/std',
    'sudo/std',
    'version/std',
    'serde',
    'safe-mix/std',
    'offchain-primitives/std',
    'substrate-session/std',
    'transaction-payment/std',
    'randomness-collective-flip/std',
    'system-rpc-runtime-api/std',
    'forum/std',
    'minting/std',
    'recurringrewards/std',
    'stake/std',
    'hiring/std',
    'versioned_store_permissions/std'
]

[dependencies.babe]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-babe'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.babe-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-babe-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-balances'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.substrate-client]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-client'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.executive]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-executive'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-grandpa'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.indices]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-indices'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-offchain-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-std'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.safe-mix]
default-features = false
version = '1.0'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.substrate-session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.sudo]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-sudo'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.srml-support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-support'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-system'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-timestamp'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.version]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-version'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.authority-discovery-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-authority-discovery-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.authority-discovery]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-authority-discovery'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.authorship]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-authorship'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.finality-tracker]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-finality-tracker'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.im-online]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-im-online'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.session]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-session'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.offences]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-offences'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.sr-staking-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-staking-primitives'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.staking]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-staking'
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.transaction-payment]
package = "srml-transaction-payment"
git = 'https://github.com/paritytech/substrate.git'
default_features = false
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.randomness-collective-flip]
package = "srml-randomness-collective-flip"
git = 'https://github.com/paritytech/substrate.git'
default_features = false
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[dependencies.system-rpc-runtime-api]
package = "srml-system-rpc-runtime-api"
git = 'https://github.com/paritytech/substrate.git'
default_features = false
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

# don't rename the dependency it is causing some strange compiler error:
# https://github.com/rust-lang/rust/issues/64450
[dependencies.srml-staking-reward-curve]
package = 'srml-staking-reward-curve'
git = 'https://github.com/paritytech/substrate.git'
default_features = false
rev = '0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3'

[build-dependencies.wasm-builder-runner]
package = 'substrate-wasm-builder-runner'
version = '1.0.4'

[dependencies.forum]
default_features = false
git = 'https://github.com/mnaamani/substrate-forum-module'
package = 'substrate-forum-module'
branch = 'use-polkadot-master-substrate-version'
# Before releasing Rome - finalize and tag release new forum and update this
# tag = 'v1.0.0'

[dependencies.minting]
default_features = false
git = 'https://github.com/Joystream/substrate-token-minting-module/'
package = 'substrate-token-mint-module'
rev = '2a0e49537a8919610be84652ee3fb96f1f185de5'

[dependencies.recurringrewards]
default_features = false
git = 'https://github.com/Joystream/substrate-recurring-reward-module'
package = 'substrate-recurring-reward-module'
rev = '5dcf286b2c45b6ee5393b71b4a176f3174a71c7f'

[dependencies.stake]
default_features = false
git = 'https://github.com/mnaamani/substrate-stake/'
package = 'substrate-stake-module'
rev = 'eb4ef9711f1c375cc59f55b74b8a4e725335f4f0'

[dependencies.hiring]
default_features = false
git = 'https://github.com/bedeho/substrate-hiring-module'
package = 'substrate-hiring-module'
rev = 'c030ae8305ef81e59934125c0927c92c4cb77ef9'

[dependencies.versioned_store_permissions]
default_features = false
git = 'https://github.com/bedeho/substrate-versioned-store-permissions-module'
package = 'substrate-versioned-store-permissions-module'
rev = 'ddff0791de3774d10f79483f6609340fede35551'