version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - '127.0.0.1:5001:5001'
      - '127.0.0.1:8080:8080'
    volumes:
      - ipfs-data:/data/ipfs
    entrypoint: ''
    command: |
      /bin/sh -c "
        set -e
        /usr/local/bin/start_ipfs config profile apply lowpower
        /usr/local/bin/start_ipfs config --json Gateway.PublicGateways '{\"localhost\": null }'
        /sbin/tini -- /usr/local/bin/start_ipfs daemon --migrate=true
      "
  chain:
    image: joystream/node
    build:
      context: .
      dockerfile: joystream-node.Dockerfile
    ports:
      - '127.0.0.1:9944:9944'
    volumes:
      - chain-data:/data
    command: --dev --ws-external --base-path /data

  colossus:
    image: joystream/apps
    restart: on-failure
    depends_on:
      - "chain"
      - "ipfs"
    build:
      context: .
      dockerfile: apps.Dockerfile
    ports:
      - '127.0.0.1:3001:3001'
    command: colossus --dev --ws-provider ws://chain:9944 --ipfs-host ipfs
    environment:
      - DEBUG=*

volumes:
  ipfs-data:
    driver: local
  chain-data:
    driver: local
