[package]
authors = ['Joystream contributors']
edition = '2018'
name = 'joystream-node-runtime'
# Follow convention: https://github.com/Joystream/substrate-runtime-joystream/issues/1
# {Authoring}.{Spec}.{Impl} of the RuntimeVersion
version = '7.0.0'

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = 'parity-scale-codec', version = '1.3.1', default-features = false, features = ['derive'] }
rstd = { package = 'sp-std', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
frame-support = { package = 'frame-support', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
frame-executive = { package = 'frame-executive', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
frame-system-rpc-runtime-api = { package = 'frame-system-rpc-runtime-api', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-arithmetic = { package = 'sp-arithmetic', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
#node-primitives = { package = 'node-primitives', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-runtime = { package = 'sp-runtime', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-offchain = { package = 'sp-offchain', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-io = { package = 'sp-io', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-core = { package = 'sp-core', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-authority-discovery = { package = 'sp-authority-discovery', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-consensus-babe = { package = 'sp-consensus-babe', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-transaction-pool = { package = 'sp-transaction-pool', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-session = { package = 'sp-session', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-grandpa = { package = 'pallet-grandpa', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-block-builder = { package = 'sp-block-builder', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-api = { package = 'sp-api', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-version = { package = 'sp-version', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sp-staking = { package = 'sp-staking', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-staking-reward-curve = { package = 'pallet-staking-reward-curve', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-babe = { package = 'pallet-babe', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-indices = { package = 'pallet-indices', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-transaction-payment = { package = 'pallet-transaction-payment', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-authorship = { package = 'pallet-authorship', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-session = { package = 'pallet-session', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-offences = { package = 'pallet-offences', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-finality-tracker = { package = 'pallet-finality-tracker', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-randomness-collective-flip = { package = 'pallet-randomness-collective-flip', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-authority-discovery = { package = 'pallet-authority-discovery', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}


system = { package = 'frame-system', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-sudo = { package = 'pallet-sudo', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-staking = { package = 'pallet-staking', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
timestamp = { package = 'pallet-timestamp', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-balances = { package = 'pallet-balances', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-im-online = { package = 'pallet-im-online', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
pallet-collective = { package = 'pallet-collective', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}

common = { package = 'pallet-common', default-features = false, path = '../runtime-modules/common'}
memo = { package = 'pallet-memo', default-features = false, path = '../runtime-modules/memo'}
forum = { package = 'pallet-forum', default-features = false, path = '../runtime-modules/forum'}
membership = { package = 'pallet-membership', default-features = false, path = '../runtime-modules/membership'}
stake = { package = 'pallet-stake', default-features = false, path = '../runtime-modules/stake'}
governance = { package = 'pallet-governance', default-features = false, path = '../runtime-modules/governance'}
hiring = { package = 'pallet-hiring', default-features = false, path = '../runtime-modules/hiring'}
minting = { package = 'pallet-token-mint', default-features = false, path = '../runtime-modules/token-minting'}
recurring-rewards = { package = 'pallet-recurring-reward', default-features = false, path = '../runtime-modules/recurring-reward'}
working-group = { package = 'pallet-working-group', default-features = false, path = '../runtime-modules/working-group'}
content-working-group = { package = 'pallet-content-working-group', default-features = false, path = '../runtime-modules/content-working-group'}
versioned-store = { package = 'pallet-versioned-store', default-features = false, path = '../runtime-modules/versioned-store'}
versioned-store-permissions = { package = 'pallet-versioned-store-permissions', default-features = false, path = '../runtime-modules/versioned-store-permissions'}
storage = { package = 'pallet-storage', default-features = false, path = '../runtime-modules/storage'}
service-discovery = { package = 'pallet-service-discovery', default-features = false, path = '../runtime-modules/service-discovery'}
proposals-engine = { package = 'pallet-proposals-engine', default-features = false, path = '../runtime-modules/proposals/engine'}
proposals-discussion = { package = 'pallet-proposals-discussion', default-features = false, path = '../runtime-modules/proposals/discussion'}
proposals-codex = { package = 'pallet-proposals-codex', default-features = false, path = '../runtime-modules/proposals/codex'}

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }


[features]
default = ['std']
no_std = []
std = [
#    'authority-discovery-primitives/std',
#    'authority-discovery/std',
#    'authorship/std',
#    'finality-tracker/std',
#    'im-online/std',
#    'session/std',
#    'offences/std',
#    'sr-staking-primitives/std',
#    'substrate-client/std',
    'rstd/std',
    'sp-io/std',
    'sp-core/std',
    'frame-support/std',
    'frame-system-rpc-runtime-api/std',
    'sp-authority-discovery/std',
    'sp-consensus-babe/std',
    'sp-block-builder/std',
    'sp-transaction-pool/std',
    'sp-offchain/std',
 #   'node-primitives/std',
    'pallet-grandpa/std',
    'pallet-babe/std',
    'pallet-im-online/std',
    'pallet-indices/std',
    'pallet-authority-discovery/std',
    'pallet-collective/std',
#    'babe/std',
#    'babe-primitives/std',
#    'executive/std',
#    'indices/std',
#    'grandpa/std',
#    'primitives/std',
#    'sr-primitives/std',
#    'version/std',
#    'safe-mix/std',
#    'offchain-primitives/std',
#    'substrate-session/std',
#    'transaction-payment/std',
#    'randomness-collective-flip/std',
#    'system-rpc-runtime-api/std',


    'serde',
    'codec/std',

    'pallet-staking/std',
    'pallet-balances/std',
    'system/std',
    'timestamp/std',
    'pallet-sudo/std',

    'forum/std',
    'minting/std',
    'recurring-rewards/std',
    'stake/std',
    'hiring/std',
    'versioned-store/std',
    'versioned-store-permissions/std',
    'common/std',
    'content-working-group/std',
    'governance/std',
    'membership/std',
    'memo/std',
    'service-discovery/std',
    'storage/std',
    'proposals-engine/std',
    'proposals-discussion/std',
    'proposals-codex/std',
    'working-group/std',
]


#[dependencies.babe]
#default-features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-babe'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.babe-primitives]
#default-features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-consensus-babe-primitives'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.substrate-client]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-client'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.executive]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-executive'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.grandpa]
#default-features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-grandpa'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.indices]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-indices'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.offchain-primitives]
#default-features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-offchain-primitives'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.primitives]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-primitives'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.safe-mix]
#default-features = false
#version = '1.0'
#
#[dependencies.substrate-session]
#default-features = false
#git = 'https://github.com/paritytech/substrate.git'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#

#
#[dependencies.authority-discovery-primitives]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-authority-discovery-primitives'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.authority-discovery]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-authority-discovery'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.authorship]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-authorship'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.finality-tracker]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-finality-tracker'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.im-online]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-im-online'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.session]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-session'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.offences]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-offences'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.sr-staking-primitives]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'sr-staking-primitives'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.staking]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-staking'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.transaction-payment]
#package = "srml-transaction-payment"
#git = 'https://github.com/paritytech/substrate.git'
#default_features = false
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.randomness-collective-flip]
#package = "srml-randomness-collective-flip"
#git = 'https://github.com/paritytech/substrate.git'
#default_features = false
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.system-rpc-runtime-api]
#package = "srml-system-rpc-runtime-api"
#git = 'https://github.com/paritytech/substrate.git'
#default_features = false
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#





