[package]
name = "joystream-node-runtime"
version = "0.9.0"
authors = ["Jsgenesis <contact@jsgenesis.com>"]

[dependencies]
rustc-hex = "1.0"
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
parity-codec = "2.2"
parity-codec-derive = "2.1"
sr-std = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
sr-io = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
srml-support = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-keyring = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
srml-balances = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
srml-consensus = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
srml-aura = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
srml-executive = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
srml-indices = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
sr-primitives = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
srml-system = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
srml-timestamp = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
srml-sudo = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-client = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5", optional = true }
sr-version = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }
substrate-consensus-aura-primitives = { git = "https://github.com/paritytech/substrate", rev = "53bf81e5" }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"substrate-client/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-executive/std",
	"srml-aura/std",
	"srml-indices/std",
	"sr-primitives/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-sudo/std",
	"sr-version/std",
	"serde_derive",
	"serde/std",
	"safe-mix/std",
	"substrate-client",
	"substrate-consensus-aura-primitives/std",
]
