[package]
authors = ['Joystream contributors']
build = 'build.rs'
edition = '2018'
name = 'joystream-node'
version = '3.0.0'
default-run = "joystream-node"

[[bin]]
name = 'joystream-node'
path = 'bin/main.rs'

[lib]
crate-type = ["cdylib", "rlib"]

#[dependencies]
#derive_more = '0.14.0'
#exit-future = '0.1.4'

#hex = '0.4'

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.1" }
serde = { version = "1.0.102", features = ["derive"] }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
jsonrpc-core = "14.2.0"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8"}
tracing = "0.1.10"
parking_lot = "0.10.0"

serde_json = '1.0'
tokio = '0.1.22'

# primitives
sp-authority-discovery = { package = 'sp-authority-discovery', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-consensus-babe = { package = 'sp-consensus-babe', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-finality-grandpa = { package = 'sp-finality-grandpa', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-core = { package = 'sp-core', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-runtime = { package = 'sp-runtime', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-timestamp = { package = 'sp-timestamp', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-finality-tracker = { package = 'sp-finality-tracker', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-inherents = { package = 'sp-inherents', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-keyring = { package = 'sp-keyring', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-io = { package = 'sp-io', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-consensus = { package = 'sp-consensus', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-transaction-pool = { package = 'sp-transaction-pool', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-api = { package = 'sp-api', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-blockchain = { package = 'sp-blockchain', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }

# client dependencies
sc-client-api = { package = 'sc-client-api', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-chain-spec = { package = 'sc-chain-spec', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-consensus = { package = 'sc-consensus', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-transaction-pool = { package = 'sc-transaction-pool', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-network = { package = 'sc-network', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-consensus-babe = { package = 'sc-consensus-babe', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'}
sc-finality-grandpa = { package = 'sc-finality-grandpa', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-client-db = { package = 'sc-client-db', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-offchain = { package = 'sc-offchain', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-rpc = { package = 'sc-rpc', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-basic-authorship = { package = 'sc-basic-authorship', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-service = { package = 'sc-service', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-tracing = { package = 'sc-tracing', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-telemetry = { package = 'sc-telemetry', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-authority-discovery = { package = 'sc-authority-discovery', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-consensus-epochs = { package = 'sc-consensus-epochs', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-keystore = { package = 'sc-keystore', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-consensus-babe-rpc = { package = 'sc-consensus-babe-rpc', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-finality-grandpa-rpc = { package = 'sc-finality-grandpa-rpc', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-rpc-api = { package = 'sc-rpc-api', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sp-block-builder = { package = 'sp-block-builder', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-contracts-rpc = { package = 'pallet-contracts-rpc', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-transaction-payment-rpc = { package = 'pallet-transaction-payment-rpc', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
substrate-frame-rpc-system = { package = 'substrate-frame-rpc-system', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
sc-executor = { package = 'sc-executor', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
frame-benchmarking = { package = 'frame-benchmarking', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }

#sc-client-api = { version = "2.0.0-rc4", path = "../../../client/api" }
#jsonrpc-core = "14.2.0"
#node-primitives = { version = "2.0.0-rc4", path = "../primitives" }
#node-runtime = { version = "2.0.0-rc4", path = "../runtime" }
#sp-runtime = { version = "2.0.0-rc4", path = "../../../primitives/runtime" }
#sp-api = { version = "2.0.0-rc4", path = "../../../primitives/api" }
#pallet-contracts-rpc = { version = "0.8.0-rc4", path = "../../../frame/contracts/rpc/" }
#pallet-transaction-payment-rpc = { version = "2.0.0-rc4", path = "../../../frame/transaction-payment/rpc/" }
#substrate-frame-rpc-system = { version = "2.0.0-rc4", path = "../../../utils/frame/rpc/system" }
#sp-transaction-pool = { version = "2.0.0-rc4", path = "../../../primitives/transaction-pool" }
#sc-consensus-babe = { version = "0.8.0-rc4", path = "../../../client/consensus/babe" }
#sc-consensus-babe-rpc = { version = "0.8.0-rc4", path = "../../../client/consensus/babe/rpc" }
#sp-consensus-babe = { version = "0.8.0-rc4", path = "../../../primitives/consensus/babe" }
#sc-keystore = { version = "2.0.0-rc4", path = "../../../client/keystore" }
#sc-consensus-epochs = { version = "0.8.0-rc4", path = "../../../client/consensus/epochs" }
#sp-consensus = { version = "0.8.0-rc4", path = "../../../primitives/consensus/common" }
#sp-blockchain = { version = "2.0.0-rc4", path = "../../../primitives/blockchain" }
#sc-finality-grandpa = { version = "0.8.0-rc4", path = "../../../client/finality-grandpa" }
#sc-finality-grandpa-rpc = { version = "0.8.0-rc4", path = "../../../client/finality-grandpa/rpc" }
#sc-rpc-api = { version = "0.8.0-rc4", path = "../../../client/rpc-api" }
#sp-block-builder = { version = "2.0.0-rc4", path = "../../../primitives/block-builder" }

# frame dependencies
pallet-indices = { package = 'pallet-indices', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-timestamp = { package = 'pallet-timestamp', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-contracts = { package = 'pallet-contracts', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
frame-system = { package = 'frame-system', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-balances = { package = 'pallet-balances', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-transaction-payment = { package = 'pallet-transaction-payment', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
frame-support = { package = 'frame-support', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-im-online = { package = 'pallet-im-online', default-features = false, git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-authority-discovery = { package = 'pallet-authority-discovery', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-staking = { package = 'pallet-staking', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
pallet-grandpa = { package = 'pallet-grandpa', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }

# node-specific dependencies
node-runtime = { package= "joystream-node-runtime", path = "../runtime" }

# CLI-specific dependencies
sc-cli = { package = 'sc-cli', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
frame-benchmarking-cli = { package = 'frame-benchmarking-cli', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }
node-inspect = { package = 'node-inspect', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4' }

# WASM-specific dependencies
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { package = 'substrate-browser-utils', git = 'https://github.com/paritytech/substrate.git', rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4', optional = true}


#[dependencies.substrate-basic-authorship]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-basic-authorship'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.babe]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-consensus-babe'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.babe-primitives]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-consensus-babe-primitives'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.codec]
#package = 'parity-scale-codec'
#version = '1.0.0'
#
#[dependencies.ctrlc]
#features = ['termination']
#version = '3.0'
#
#[dependencies.inherents]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-inherents'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.network]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-network'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.primitives]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-primitives'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.sr-io]
#git = 'https://github.com/paritytech/substrate.git'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.substrate-cli]
#git = 'https://github.com/paritytech/substrate.git'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.substrate-client]
#git = 'https://github.com/paritytech/substrate.git'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.substrate-executor]
#git = 'https://github.com/paritytech/substrate.git'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.substrate-service]
#git = 'https://github.com/paritytech/substrate.git'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.transaction-pool]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-transaction-pool'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.substrate-telemetry]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-telemetry'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.grandpa]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-finality-grandpa'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.grandpa-primitives]
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-finality-grandpa-primitives'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.im-online]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'srml-im-online'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.substrate-rpc]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-rpc'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.authority-discovery]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-authority-discovery'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.client-db]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-client-db'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.runtime-primitives]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'sr-primitives'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.offchain]
#default_features = false
#git = 'https://github.com/paritytech/substrate.git'
#package = 'substrate-offchain'
#rev = 'c37bb08535c49a12320af7facfd555ce05cce2e8'
#
#[dependencies.libp2p]
#version = '0.13.2'
#default-features = false

[build-dependencies]
vergen = '3'
