name: run-network-tests-branch
on:
  push:
  workflow_dispatch:

jobs:
  prepare_docker_images:
    name: Build new images
    runs-on: ubuntu-latest
    outputs:
      joystream_node_tag: ${{ steps.docker_build.outputs.tag }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - id: docker_build
        name: Build and publish docker images
        run: |
          export RUNTIME_CODE_SHASUM=`scripts/runtime-code-shasum.sh`
          function docker_tag_exists() {
            curl --silent -f -lSL https://index.docker.io/v1/repositories/joystream/node/tags/$1 > /dev/null
          }
          if ! docker_tag_exists ${RUNTIME_CODE_SHASUM}; then
              docker-compose build
              docker image tag joystream/node joystream/node:${RUNTIME_CODE_SHASUM}
              docker push joystream/node:${RUNTIME_CODE_SHASUM}
          fi
          echo "::set-output name=tag::${RUNTIME_CODE_SHASUM}"

  run_network_tests_1:
    name: Network Integration Runtime Tests
    needs: prepare_docker_images
    runs-on: ubuntu-latest
    env:
      JOYSTREAM_NODE_TAG: ${{ needs.prepare_docker_images.outputs.joystream_node_tag }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages and dependencies
        run: yarn install --frozen-lockfile
      - name: Ensure tests are runnable
        run: yarn workspace network-tests build
      - name: Pull joystream/node image from Dockerhub
        run: docker-compose pull
      - name: Start chain
        run: docker-compose up -d
      - name: Execute network tests
        run: yarn workspace network-tests test

  run_network_tests_2:
    name: Query Node Tests (Placeholder)
    needs: prepare_docker_images
    runs-on: ubuntu-latest
    env:
      JOYSTREAM_NODE_TAG: ${{ needs.prepare_docker_images.outputs.joystream_node_tag }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages and dependencies
        run: yarn install --frozen-lockfile
      - name: Ensure tests are runnable
        run: yarn workspace network-tests build
      - name: Pull joystream/node image from Dockerhub
        run: docker-compose pull
      - name: Start chain
        run: docker-compose up -d
      # - name: Execute network tests
      #   run: yarn workspace network-tests test

  run_network_tests_3:
    name: Storage Node Tests
    needs: prepare_docker_images
    runs-on: ubuntu-latest
    env:
      JOYSTREAM_NODE_TAG: ${{ needs.prepare_docker_images.outputs.joystream_node_tag }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages and dependencies
        run: |
          yarn install --frozen-lockfile
          yarn workspace storage-node build
      - name: Build storage node
        run: yarn workspace storage-node build
      - name: Pull joystream/node image from Dockerhub
        run: docker-compose pull
      - name: Start chain
        run: docker-compose up -d
      - name: Execute tests
        run: DEBUG=* yarn storage-cli dev-init