name: run-network-tests
on:
  pull_request:
    types: [labeled, synchronize]
  workflow_dispatch:

jobs:
  run_network_tests:
    name: Network Integration Tests
    if: contains(github.event.pull_request.labels.*.name, 'run-network-tests') || github.event.action == null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages and dependencies
        run: yarn install --frozen-lockfile
      - name: Ensure tests are runnable
        run: yarn workspace joystream-testing build
      - name: Configure block production to 2000ms (fatser tests)
        run: ./scripts/alter-block-creation-time.sh
      - name: Build and start chain
        run: docker-compose --file devops/dockerfiles/node-and-runtime/docker-compose.yml up -d
      - name: Execute network tests
        run: yarn workspace joystream-testing test
