name: run-network-tests
on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  run_network_tests:
    if: github.event.label.name == 'run-network-tests' || github.event.action == null
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build npm packages
        run: |
          yarn install --frozen-lockfile
          yarn workspace joystream-testing install
      - name: set block production to 2000ms for faster tests
        run: ./scripts/alter-block-creation-time.sh
      - name: start network
        run: docker-compose -f devops/dockerfiles/node-and-runtime/build-and-run-single-node-dev.yml up -d
      - name: execute tests
        run: yarn workspace joystream-testing test
