name: run-network-tests
on:
  pull_request:
    types: [labeled, synchronize]
  workflow_dispatch:

jobs:
  run_network_tests:
    name: Network Integration Tests
    if: contains(github.event.pull_request.labels.*.name, 'run-network-tests') || github.event.action == null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages and dependencies
        run: yarn install --frozen-lockfile
      - name: Ensure tests are runnable
        run: yarn workspace network-tests build
      # TODO: determin if we will build a new joystream/node image from source
      # our use a prebuilt image. Build if PR has joystream-node or runtime code changes
      # For prebuilt image set NODE_TAG env var to select tag. Use the PR base branch, 
      # ie. the 'target' branch of the PR. For now we just use hardcoded the pre-built image
      # defined in the docker-compose file.
      # When building from source tweak the block production setting for faster tests.
      # - name: Configuring shorter block production time
      #   run: ./scripts/alter-block-creation-time.sh
      - name: Build and start chain
        run: docker-compose --file docker-compose-no-build.yml up -d
      - name: Execute network tests
        run: yarn workspace network-tests test
