name: run-network-tests
on: 
  push:
  workflow_dispatch:

jobs:
  run_network_tests:
    name: Network Integration Tests (branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages and dependencies
        run: yarn install --frozen-lockfile
      - name: Ensure tests are runnable
        run: yarn workspace network-tests build
      - name: Start chain
        run: |
          JOYSTREAM_NODE_TAG=latest docker-compose build
          JOYSTREAM_NODE_TAG=latest docker-compose up -d
      - name: Execute network tests
        run: yarn workspace network-tests test
