name: run-network-tests
on:
  pull_request:
    types: [labeled, synchronize]
  workflow_dispatch:

jobs:
  run_network_tests:
    name: Network Integration Tests
    if: contains(github.event.pull_request.labels.*.name, 'run-network-tests') || github.event.action == null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: technote-space/get-diff-action@v3
        with:
          PREFIX_FILTER: |
            node
            runtime-modules
            utils/chain-spec-builder
          SUFFIX_FILTER: |
            .rs
          FILES: |
            Cargo.lock
            Cargo.toml
      - name: Install packages and dependencies
        run: yarn install --frozen-lockfile
      - name: Ensure tests are runnable
        run: yarn workspace network-tests build
      - name: Maybe build joystream/node Docker image from source
        run: |
          echo "joystream-node source modified. Will build from source."  
          export JOYSTREAM_NODE_TAG=${{ github.event.pull_request.base.ref }}
          docker-compose build
        if: env.GIT_DIFF
      - name: Start chain
        run: JOYSTREAM_NODE_TAG=${{ github.event.pull_request.base.ref }} docker-compose up -d
      - name: Execute network tests
        run: yarn workspace network-tests test
